name: Bug Report
description: Report issues and bugs encountered while using Slimefun 4
labels:
  - "🐞 Bug"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the Slimefun issue reporting system!
        
        Before reporting, please confirm:
        - You have checked the [latest version](https://github.com/SlimefunGuguProject/Slimefun4/releases) to see if the issue you encountered has been fixed
        - You have searched existing [issues](https://github.com/SlimefunGuguProject/Slimefun4/issues) to see if similar issues have been found
        
        If your report is vague or does not conform to the template, it will be closed directly by us.

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please describe the issue you encountered in detail here
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
       label: Reproducibility Rate
       description: Select the probability of the issue occurring
       options:
         - Cannot Reproduce
         - Low Occasional
         - High Occasional
         - Always Reproducible
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Briefly explain how to reproduce this issue
      placeholder: |
        Briefly explain how to reproduce this issue
        You can use list format like 1.  2.  3., or any other appropriate format
        If this issue is not easy to reproduce, please try to describe the situation when it occurred
    validations:
      required: true

  - type: dropdown
    id: server-platform-type
    attributes:
      label: Server Type
      description: |
        Select the server you are using, such as `Paper`
        Note: The Chinese version repository does not provide any support for **hybrid servers** (such as Arclight, CatServer, which support both plugins and Mods), please solve it yourself
      options:
        - Paper
        - Leaves
        - Purpur
        - Airplane
        - Pufferfish
        - Leaf
        - Mirai
        - Other Server (Please describe in detail in `Issue Description`)
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      options:
        - 1.21.9~1.21.10
        - 1.21.7~1.21.8
        - 1.21.6
        - 1.21.5
        - 1.21.4
        - 1.21.2~1.21.3
        - 1.21~1.21.1
        - 1.20.x
        - 1.19.x
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - 1.15.x
        - 1.14.x
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    validations:
      required: true
    attributes:
      label: Slimefun Version
      description: |
        **Do not fill in "latest version", otherwise your report will be closed immediately**
        Please screenshot or copy the output after executing the command "/sf versions".
      placeholder: Slimefun 2025.1

  - type: textarea
    id: other-plugin
    attributes:
      label: Server Plugin List
      description: Provide your server plugin list, you can get it by executing the command /plugins.
      placeholder: |
        Plugin: Version

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: If necessary, you can add other information below
