name: Translation Report
description: Report translation issues in Slimefun 4 Chinese Version
labels:
- "📜 Translation | Translation Issue"

body:
- type: markdown
  attributes:
    value: |
      Thank you for using the Slimefun issue reporting system!
      
      Before reporting, please confirm:
      - You have checked the [latest version](https://github.com/SlimefunGuguProject/Slimefun4/releases) to see if the issue you encountered has been fixed
      - You have searched existing [issues](https://github.com/SlimefunGuguProject/Slimefun4/issues) to see if similar issues have been found
      
      If your report is vague or does not conform to the template, it will be closed directly by us.

- type: textarea
  id: issue-description
  attributes:
    label: Translation Issue Description
    description: Please describe the issue you encountered in detail here
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: Translation Error/Missing Location
    description: Briefly explain the location of the translation error/missing translation here
  validations:
    required: true

- type: textarea
  id: slimefun-version
  validations:
    required: true
  attributes:
    label: Slimefun Version
    description: |
      **Do not fill in "latest version", otherwise your report will be closed immediately**
      Please screenshot or copy the output after executing the command "/sf versions".
    placeholder: Slimefun 2025.1

- type: textarea
  id: additional
  attributes:
    label: Additional Information
    description: If necessary, you can add other information below
